# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "four-equals-ten"
version = "0.1.0"
edition = "2021"

# for flamegraph (disable when non-fg benchmarking)
# [profile.release]
# debug = true

[dependencies]
